project:
  type: website
  output-dir: docs

website:
  title: "Maiko Hata"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Home
        href: index.qmd
      - text: Projects & Workshops
        href: posts.qmd

format:
  html:
    code-fold: true
    code: false
    theme:
      - minty
      - brand
    fontawesome: true
    css: styles.css
    toc: true
    toc-depth: 2

execute:
  warning: false
  message: false

editor: visual
