project:
  type: website
  output-dir: docs

website:
  title: "Maiko Hata"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: posts.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://maihata.github.io/finalproj/

format:
  html:
    code-fold: true
    code: false
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
    toc-depth: 2

execute:
  warning: false
  message: false

editor: visual
