project:
  type: website
  output-dir: docs

website:
  title: "Maiko Hata"
  navbar:
    collapse: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd 
      - text: Projects & Workshops
        href: posts.qmd
      - text: CV
        href: images/Maiko_CV_25.pdf
        target: _blank
      - icon: envelope
        href: mailto:hata@uoregon.edu
      - icon: linkedin
        href: https://linkedin.com/in/maikohata
        target: _blank

format:
  html:
    theme: minty
    toc: true
    page-layout: full