project:
  type: website
  output-dir: docs

website:
  title: "Maiko Hata"
  navbar:
    left:
      - text: About
        href: about.qmd 
      - text: Home
        href: index.qmd
      - text: Projects & Workshops
        href: posts.qmd
      - href: images/Maiko_CV.pdf
        target: _blank
        text: CV
      - href: mailto:hata@uoregon.edu
        text: "<i class='fa-solid fa-envelope' title='Email'></i>"
      - href: https://linkedin.com/in/maikohata
        target: _blank
        text: "<i class='fa-brands fa-linkedin' title='LinkedIn'></i>"
      
 
  page-footer:
    left: "© 2025 Maiko Hata"
    right: >
      Built with {{< fa heart title="love" >}}, 
      [{{< fa brands github title="GitHub" >}}](https://github.com/maikohata){target=_blank}, 
      and [Quarto](https://quarto.org){target=_blank}

format:
  html:
    theme: minty
    css: styles.css   # optional; delete this line if you're not using custom CSS
    toc: true
    page-layout: full
