project:
  type: website
  output-dir: docs

website:
  title: "Maiko Hata"
  navbar:
    collapse: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd 
      - text: Projects & Workshops
        href: posts.qmd
      - text: CV
        href: images/Maiko_CV.pdf
        target: _blank
      - icon: envelope
        href: mailto:hata@uoregon.edu
      - icon: linkedin
        href: https://linkedin.com/in/maikohata
        target: _blank
  page-footer:
    left: "© 2025 Maiko Hata"
    right: >
      Built with <i class="fa-solid fa-heart" title="love"></i>, 
      <a href="https://github.com/maikohata" target="_blank">
        <i class="fa-brands fa-github" title="GitHub"></i>
      </a>, 
      and <a href="https://quarto.org" target="_blank">Quarto</a>

format:
  html:
    theme: minty
    toc: true
    page-layout: full
    title-block-banner: false
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
